### ISSUE TITLE
Decoded string still have words that are not in lexicon with KenLMScorer

### ISSUE THREAD

**Issue by ybzhou** [ryanleary/pytorch-ctc#10]
When using LM based scorer, I still see words that are not in the lexicon appearing. Is it correct behavior? What beam search strategy is used, is it the same as described in https://arxiv.org/pdf/1408.2873.pdf ?

Thanks.

**Comment by ryanleary** [comment]
There is a low, but non-zero, probability assigned to words not in the lexicon. See https://github.com/ryanleary/pytorch-ctc/blob/master/pytorch_ctc/src/ctc_beam_scorer_klm.h#L95

**Comment by ybzhou** [comment]
I see, thanks for the reply. After changing it to a really small value it worked.

**Comment by ryanleary** [comment]
I'll expose this in a future version as a configuration parameter in Python. See #11.
