### ISSUE TITLE
error: invalid argument '-std=c++11' not allowed with 'C/ObjC' error: command 'gcc' failed with exit status 1

### ISSUE THREAD

**Issue by lxj0276** [ryanleary/pytorch-ctc#12]
when I ran the command line:
CC=/path/to/gcc-5 CXX=/path/to/g++-5 python setup.py install
it shows the error info like:
error: invalid argument '-std=c++11' not allowed with 'C/ObjC' error: command 'gcc' failed with exit status 1
my os is Macos Sierra,can anybody help me?

**Comment by Romainpaulus** [comment]
You're probably using a wrong version of `gcc`. This command fixed the issue for me on Mac:
```CC=/usr/local/bin/gcc-5 CXX=/usr/local/bin/g++-5 python setup.py install```

**Comment by ryanleary** [comment]
Indeed. Feel free to leave another comment if the above doesn't solve your issue.

**Comment by davideuler** [comment]
On mac m1 with Big Sur:

` CC=$(which gcc-11) CXX=$(which g++-11) python setup.py  install`
